### ISSUE TITLE
Local LLM and OpenAI Chat Completions API

### ISSUE THREAD

**Issue by norimudo** [AIVTDevPKevin/AI-VTuber-System#3]
I will make a request again. Sorry for the stupid questions. I'm just learning how to work with Python and LLM. I'm trying to understand how you implemented the OpenAI API. 
Task: I want to run my local LLM on your app, running on ollama and using the OpenAI Chat Completions API. But the code examples that ollama offers have lines indicating curl and models; there are no such lines anywhere in your code. Can you give some quick help/reference on how I can implement all this?

**Comment by AIVTDevPKevin** [comment]
Actually, the version I'm working on privately right now has Ollama integrated.
On the LLM page, you can pick the model that's loaded locally on Ollama. But you need to set up the whole Ollama environment outside and install the Python libraries that Ollama uses into the AIVT system.
That's why I haven't made it open-source. If you're interested in learning how to integrate Ollama into the AIVT system, You can message me on X, and I will give you my discord id. 😇

**Comment by norimudo** [comment]
Ok, thanks. Sent you a message on X
